name: "Setup and Test on Push Events"

on:
  push:
    branches:
      - "feature/*" # matches every branch containing 'feature/'
      - "bugfix/*" # matches every branch containing 'bugfix/'
      - "hotfix/*" # matches every branch containing 'hotfix/
      - "!main" # excludes main branch
  release:
    types: [created]

jobs:
  build:
    name: Setup, Build, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"] # Config the virtual env - Python version 3.11 will be used only.

    permissions:
      contents: "read"
      id-token: "write" # Add "id-token" with the intended permissions.

    steps:
      # Checkout GitHub branch's config
      - name: Checkout
        uses: actions/checkout@v4

      # Set up the Python version
      - name: Set up the Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt

      # Run tests and output results in JUnit format and parts that lack test coverage
      - name: Run tests
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=entity_recognition_service --cov-report=html --cov-report=xml

      # New step to upload JUnit test results
      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: junit/test-results.xml

      # New step to upload Coverage HTML report
      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/

      # New step to upload Coverage XML report
      - name: Upload XML Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: xml-coverage-report
          path: coverage.xml